### ISSUE TITLE
PermissionError...

### ISSUE THREAD

**Issue by konetom** [abarker/pdfCropMargins#31]
Hi,

I installed your tool: <pre>pip install pdfCropMargins --upgrade --user </pre>
I'm using Win10 Pro. Local bin is in the Path.
After reboot I tried this command in CLI
<pre>pdf-crop-margins -v -s -u name_of_my_file.pdf</pre><br>

But unfortunatelly I got this error message (even multiple files I tried to use for the same command):
<pre>
Unexpected error:  class 'PermissionError'<br>
Error message   :  [WinError 32] The process cannot access the file because it is being used by another process: <br>
'C:\\Users\\tomas\\AppData\\Local\\Temp\\pdfCropMarginsTmpDir_ai2f6zow\\pdfCropMarginsTmp_pecp2k1b.pdf'
</pre>

Thanks for any help!

**Comment by abarker** [comment]
I can't reproduce the problem on Windows 10 Pro with the latest updates.  It seems like a strange error because it is occurring in a file written to a temp directory that was created by Python.  It would help to have the full verbose output (with `-v`) to better diagnose what is going on, what versions you are using, and where exactly the error occurs.

**Comment by wfjsw** [comment]
```
Processing the PDF with pdfCropMargins (version 1.0.4)...
Python version: ('3', '9', '1')
System type: Windows

The input document's filename is:
    Java语言程序设计(第2版）_1-200.pdf

Using the default-generated output filename.

The output document's filename will be:
    C:\Users\cnwfj\Downloads\Java语言程序设计(第2版）_1-200_cropped.pdf

The absolute pre-crops to be applied to each margin, in units of bp, are:
    [0.0, 0.0, 0.0, 0.0]

The percentages of margins to retain are:
    [10.0, 10.0, 10.0, 10.0]

The absolute offsets to be applied to each margin, in units of bp, are:
    [0.0, 0.0, 0.0, 0.0]

The uniform order statistics to apply to each margin, in units of bp, are:
    []

For the full page size, using values from the PDF box
specified by the intersection of these boxes: ['m', 'c']

The input document has 200 pages.

The document's metadata, if set:

   The Author attribute set in the input document is:
      None
   The Creator attribute set in the input document is:
      PDFsam Basic v4.2.3
   The Producer attribute set in the input document is:
      SAMBox 2.2.13
   The Subject attribute set in the input document is:
      None
   The Title attribute set in the input document is:
      None

All the pages of the document will be cropped.

Original full page sizes, in PDF format (lbrt):
        1   rot = 0      [0, 0, 1440, 1976]
        2   rot = 0      [0, 0, 1440, 1976]
        3   rot = 0      [0, 0, 1440, 1976]
        4   rot = 0      [0, 0, 1440, 1976]
        5   rot = 0      [0, 0, 1440, 1976]
        6   rot = 0      [0, 0, 1440, 1976]
        7   rot = 0      [0, 0, 1440, 1976]
        8   rot = 0      [0, 0, 1440, 1976]
        9   rot = 0      [0, 0, 1440, 1976]
        10   rot = 0     [0, 0, 1440, 1976]
        11   rot = 0     [0, 0, 1440, 1976]
        12   rot = 0     [0, 0, 1440, 1976]
        13   rot = 0     [0, 0, 1440, 1976]
        14   rot = 0     [0, 0, 1440, 1976]
        15   rot = 0     [0, 0, 1440, 1976]
        16   rot = 0     [0, 0, 1440, 1976]
        17   rot = 0     [0, 0, 1440, 1976]
        18   rot = 0     [0, 0, 1440, 1976]
        19   rot = 0     [0, 0, 1440, 1976]
        20   rot = 0     [0, 0, 1440, 1976]
        21   rot = 0     [0, 0, 1440, 1976]
        22   rot = 0     [0, 0, 1440, 1976]
        23   rot = 0     [0, 0, 1440, 1976]
        24   rot = 0     [0, 0, 1440, 1976]
        25   rot = 0     [0, 0, 1440, 1976]
        26   rot = 0     [0, 0, 1440, 1976]
        27   rot = 0     [0, 0, 1440, 1976]
        28   rot = 0     [0, 0, 1440, 1976]
        29   rot = 0     [0, 0, 1440, 1976]
        30   rot = 0     [0, 0, 1440, 1976]
        31   rot = 0     [0, 0, 1440, 1976]
        32   rot = 0     [0, 0, 1440, 1976]
        33   rot = 0     [0, 0, 1440, 1976]
        34   rot = 0     [0, 0, 1440, 1976]
        35   rot = 0     [0, 0, 1440, 1976]
        36   rot = 0     [0, 0, 1440, 1976]
        37   rot = 0     [0, 0, 1440, 1976]
        38   rot = 0     [0, 0, 1440, 1976]
        39   rot = 0     [0, 0, 1440, 1976]
        40   rot = 0     [0, 0, 1440, 1976]
        41   rot = 0     [0, 0, 1440, 1976]
        42   rot = 0     [0, 0, 1440, 1976]
        43   rot = 0     [0, 0, 1440, 1976]
        44   rot = 0     [0, 0, 1440, 1976]
        45   rot = 0     [0, 0, 1440, 1976]
        46   rot = 0     [0, 0, 1440, 1976]
        47   rot = 0     [0, 0, 1440, 1976]
        48   rot = 0     [0, 0, 1440, 1976]
        49   rot = 0     [0, 0, 1440, 1976]
        50   rot = 0     [0, 0, 1440, 1976]
        51   rot = 0     [0, 0, 1440, 1976]
        52   rot = 0     [0, 0, 1440, 1976]
        53   rot = 0     [0, 0, 1440, 1976]
        54   rot = 0     [0, 0, 1440, 1976]
        55   rot = 0     [0, 0, 1440, 1976]
        56   rot = 0     [0, 0, 1440, 1976]
        57   rot = 0     [0, 0, 1440, 1976]
        58   rot = 0     [0, 0, 1440, 1976]
        59   rot = 0     [0, 0, 1440, 1976]
        60   rot = 0     [0, 0, 1440, 1976]
        61   rot = 0     [0, 0, 1440, 1976]
        62   rot = 0     [0, 0, 1440, 1976]
        63   rot = 0     [0, 0, 1440, 1976]
        64   rot = 0     [0, 0, 1440, 1976]
        65   rot = 0     [0, 0, 1440, 1976]
        66   rot = 0     [0, 0, 1440, 1976]
        67   rot = 0     [0, 0, 1440, 1976]
        68   rot = 0     [0, 0, 1440, 1976]
        69   rot = 0     [0, 0, 1440, 1976]
        70   rot = 0     [0, 0, 1440, 1976]
        71   rot = 0     [0, 0, 1440, 1976]
        72   rot = 0     [0, 0, 1440, 1976]
        73   rot = 0     [0, 0, 1440, 1976]
        74   rot = 0     [0, 0, 1440, 1976]
        75   rot = 0     [0, 0, 1440, 1976]
        76   rot = 0     [0, 0, 1440, 1976]
        77   rot = 0     [0, 0, 1440, 1976]
        78   rot = 0     [0, 0, 1440, 1976]
        79   rot = 0     [0, 0, 1440, 1976]
        80   rot = 0     [0, 0, 1440, 1976]
        81   rot = 0     [0, 0, 1440, 1976]
        82   rot = 0     [0, 0, 1440, 1976]
        83   rot = 0     [0, 0, 1440, 1976]
        84   rot = 0     [0, 0, 1440, 1976]
        85   rot = 0     [0, 0, 1440, 1976]
        86   rot = 0     [0, 0, 1440, 1976]
        87   rot = 0     [0, 0, 1440, 1976]
        88   rot = 0     [0, 0, 1440, 1976]
        89   rot = 0     [0, 0, 1440, 1976]
        90   rot = 0     [0, 0, 1440, 1976]
        91   rot = 0     [0, 0, 1440, 1976]
        92   rot = 0     [0, 0, 1440, 1976]
        93   rot = 0     [0, 0, 1440, 1976]
        94   rot = 0     [0, 0, 1440, 1976]
        95   rot = 0     [0, 0, 1440, 1976]
        96   rot = 0     [0, 0, 1440, 1976]
        97   rot = 0     [0, 0, 1440, 1976]
        98   rot = 0     [0, 0, 1440, 1976]
        99   rot = 0     [0, 0, 1440, 1976]
        100   rot = 0    [0, 0, 1440, 1976]
        101   rot = 0    [0, 0, 1440, 1976]
        102   rot = 0    [0, 0, 1440, 1976]
        103   rot = 0    [0, 0, 1440, 1976]
        104   rot = 0    [0, 0, 1440, 1976]
        105   rot = 0    [0, 0, 1440, 1976]
        106   rot = 0    [0, 0, 1440, 1976]
        107   rot = 0    [0, 0, 1440, 1976]
        108   rot = 0    [0, 0, 1440, 1976]
        109   rot = 0    [0, 0, 1440, 1976]
        110   rot = 0    [0, 0, 1440, 1976]
        111   rot = 0    [0, 0, 1440, 1976]
        112   rot = 0    [0, 0, 1440, 1976]
        113   rot = 0    [0, 0, 1440, 1976]
        114   rot = 0    [0, 0, 1440, 1976]
        115   rot = 0    [0, 0, 1440, 1976]
        116   rot = 0    [0, 0, 1440, 1976]
        117   rot = 0    [0, 0, 1440, 1976]
        118   rot = 0    [0, 0, 1440, 1976]
        119   rot = 0    [0, 0, 1440, 1976]
        120   rot = 0    [0, 0, 1440, 1976]
        121   rot = 0    [0, 0, 1440, 1976]
        122   rot = 0    [0, 0, 1440, 1976]
        123   rot = 0    [0, 0, 1440, 1976]
        124   rot = 0    [0, 0, 1440, 1976]
        125   rot = 0    [0, 0, 1440, 1976]
        126   rot = 0    [0, 0, 1440, 1976]
        127   rot = 0    [0, 0, 1440, 1976]
        128   rot = 0    [0, 0, 1440, 1976]
        129   rot = 0    [0, 0, 1440, 1976]
        130   rot = 0    [0, 0, 1440, 1976]
        131   rot = 0    [0, 0, 1440, 1976]
        132   rot = 0    [0, 0, 1440, 1976]
        133   rot = 0    [0, 0, 1440, 1976]
        134   rot = 0    [0, 0, 1440, 1976]
        135   rot = 0    [0, 0, 1440, 1976]
        136   rot = 0    [0, 0, 1440, 1976]
        137   rot = 0    [0, 0, 1440, 1976]
        138   rot = 0    [0, 0, 1440, 1976]
        139   rot = 0    [0, 0, 1440, 1976]
        140   rot = 0    [0, 0, 1440, 1976]
        141   rot = 0    [0, 0, 1440, 1976]
        142   rot = 0    [0, 0, 1440, 1976]
        143   rot = 0    [0, 0, 1440, 1976]
        144   rot = 0    [0, 0, 1440, 1976]
        145   rot = 0    [0, 0, 1440, 1976]
        146   rot = 0    [0, 0, 1440, 1976]
        147   rot = 0    [0, 0, 1440, 1976]
        148   rot = 0    [0, 0, 1440, 1976]
        149   rot = 0    [0, 0, 1440, 1976]
        150   rot = 0    [0, 0, 1440, 1976]
        151   rot = 0    [0, 0, 1440, 1976]
        152   rot = 0    [0, 0, 1440, 1976]
        153   rot = 0    [0, 0, 1440, 1976]
        154   rot = 0    [0, 0, 1440, 1976]
        155   rot = 0    [0, 0, 1440, 1976]
        156   rot = 0    [0, 0, 1440, 1976]
        157   rot = 0    [0, 0, 1440, 1976]
        158   rot = 0    [0, 0, 1440, 1976]
        159   rot = 0    [0, 0, 1440, 1976]
        160   rot = 0    [0, 0, 1440, 1976]
        161   rot = 0    [0, 0, 1440, 1976]
        162   rot = 0    [0, 0, 1440, 1976]
        163   rot = 0    [0, 0, 1440, 1976]
        164   rot = 0    [0, 0, 1440, 1976]
        165   rot = 0    [0, 0, 1440, 1976]
        166   rot = 0    [0, 0, 1440, 1976]
        167   rot = 0    [0, 0, 1440, 1976]
        168   rot = 0    [0, 0, 1440, 1976]
        169   rot = 0    [0, 0, 1440, 1976]
        170   rot = 0    [0, 0, 1440, 1976]
        171   rot = 0    [0, 0, 1440, 1976]
        172   rot = 0    [0, 0, 1440, 1976]
        173   rot = 0    [0, 0, 1440, 1976]
        174   rot = 0    [0, 0, 1440, 1976]
        175   rot = 0    [0, 0, 1440, 1976]
        176   rot = 0    [0, 0, 1440, 1976]
        177   rot = 0    [0, 0, 1440, 1976]
        178   rot = 0    [0, 0, 1440, 1976]
        179   rot = 0    [0, 0, 1440, 1976]
        180   rot = 0    [0, 0, 1440, 1976]
        181   rot = 0    [0, 0, 1440, 1976]
        182   rot = 0    [0, 0, 1440, 1976]
        183   rot = 0    [0, 0, 1440, 1976]
        184   rot = 0    [0, 0, 1440, 1976]
        185   rot = 0    [0, 0, 1440, 1976]
        186   rot = 0    [0, 0, 1440, 1976]
        187   rot = 0    [0, 0, 1440, 1976]
        188   rot = 0    [0, 0, 1440, 1976]
        189   rot = 0    [0, 0, 1440, 1976]
        190   rot = 0    [0, 0, 1440, 1976]
        191   rot = 0    [0, 0, 1440, 1976]
        192   rot = 0    [0, 0, 1440, 1976]
        193   rot = 0    [0, 0, 1440, 1976]
        194   rot = 0    [0, 0, 1440, 1976]
        195   rot = 0    [0, 0, 1440, 1976]
        196   rot = 0    [0, 0, 1440, 1976]
        197   rot = 0    [0, 0, 1440, 1976]
        198   rot = 0    [0, 0, 1440, 1976]
        199   rot = 0    [0, 0, 1440, 1976]
        200   rot = 0    [0, 0, 1440, 1976]

Copied these items from the document catalog:
   /Type /Version /PieceInfo
Skipped copy of these items from the document catalog:
   /Pages

The document was not previously cropped by pdfCropMargins.

Writing out the PDF with the CropBox and MediaBox redefined.

Rendering the PDF to images using the mupdf program,
this may take a while...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\external_program_calls.py", line 232, in remove_program_temp_directory
    shutil.rmtree(program_temp_directory)
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:  'C:\\Users\\cnwfj\\AppData\\Local\\Temp\\pdfCropMarginsTmpDir_nmjgi4ta\\pdfCropMarginsTmp_35r_r68v.pdf'

Caught an unexpected exception in the pdfCropMargins program.
Unexpected error:  <class 'AttributeError'>
Error message   :  'DisplayList' object has no attribute 'getPixmap'

  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\pdfCropMargins.py", line 61, in main
    crop()
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\pdfCropMargins.py", line 172, in crop
    main_crop(argv_list)
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\main_pdfCropMargins.py", line 1439, in main_crop
    process_pdf_file(input_doc_fname, fixed_input_doc_fname, output_doc_fname)
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\main_pdfCropMargins.py", line 1247, in process_pdf_file
    bounding_box_list = get_bounding_box_list(doc_with_crop_and_media_boxes_name,
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\calculate_bounding_boxes.py", line 102, in get_bounding_box_list
    bbox_list = get_bounding_box_list_render_image(input_doc_fname, input_doc)
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\calculate_bounding_boxes.py", line 151, in get_bounding_box_list_render_image
    image_list = get_image_list_mupdf(pdf_file_name) # Images are PPM bytes objects.
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\calculate_bounding_boxes.py", line 282, in get_image_list_mupdf
    page_images = [document_pages.get_page_ppm_for_crop(i) for i in range(num_pages)]
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\calculate_bounding_boxes.py", line 282, in <listcomp>
    page_images = [document_pages.get_page_ppm_for_crop(i) for i in range(num_pages)]
  File "c:\users\cnwfj\appdata\local\programs\python\python39\lib\site-packages\pdfCropMargins\pymupdf_routines.py", line 150, in get_page_ppm_for_crop
    pixmap = page_crop_display_list.getPixmap(matrix=fitz.Identity,

```

**Comment by abarker** [comment]
@wfjsw, your problem seems to be another bug related to the renaming effort going on in the PyMuPDF dependency.  One solution would be to revert temporarily back to an older version of PyMuPDF.  Something like:
```
pip install pymupdf==pymupdf-1.18.8
```
I'll push out a patched version of pdfCropMargins soon.

I'm not sure if that permission error (which is secondary to another bug) is related to the earlier bug in this issue or not.  Thanks for the report.

**Comment by abarker** [comment]
@wfjsw, a patched version of pdfCropMargins has been pushed out as version 1.0.5.

**Comment by BlingBlingKing** [comment]
Nether of the solution worked. 

pymupdf version 1.18.8
pdfCropMargins version 1.0.5

        5595   rot = 0   [70, 20, 542, 772]
        5596   rot = 0   [70, 20, 542, 772]
        5597   rot = 0   [70, 20, 542, 772]
        5598   rot = 0   [70, 20, 542, 772]
        5599   rot = 0   [70, 20, 542, 772]
        5600   rot = 0   [70, 20, 542, 772]

Copied these items from the document catalog:
   /PageMode /OpenAction /PageLayout /Names /Metadata /Type /StructTreeRoot /Threads /Outlines /PageLabels /ViewerPreferences
Skipped copy of these items from the document catalog:
   /Pages

The document was not previously cropped by pdfCropMargins.

Writing out the PDF with the CropBox and MediaBox redefined.

Error in pdfCropMargins: The pyPdf program failed in trying to
write out a PDF file of the document.  The document may be
corrupted.  If you have Ghostscript, try using the '--gsFix'
option (assuming you are not already using it).
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramLanguage\Python\venv\lib\site-packages\pdfCropMargins\external_program_calls.py", line 232, in remove_program_temp_directory
    shutil.rmtree(program_temp_directory)
  File "C:\Program Files\Python37\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python37\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pdfCropMarginsTmpDir_0gt6n_nw\\pdfCropMarginsTmp_6tpc3i0l.pdf'

**Comment by abarker** [comment]
I can't reproduce the error.  I ran the program on Windows with pdfCropMargins version 1.05, pymupdf 1.19.6, pysimplegui 4.59.0, and pillow 9.1.0 (these were all the latest versions).  Have you updated the dependencies?  Does this error occur on every file or only on certain files?

**Comment by ntnguyen1234** [comment]
I think the problem appears again after upgrading pymupdf to 1.20.0.

**Comment by abarker** [comment]
The PyMuPDF 1.20.0 release removed some deprecated method names, which was causing problems.  I just pushed out version 1.0.7 to fix that issue.  Are you still getting the permission error?

**Comment by ntnguyen1234** [comment]
> The PyMuPDF 1.20.0 release removed some deprecated method names, which was causing problems. I just pushed out version 1.0.7 to fix that issue. Are you still getting the permission error?

It works perfectly now 👍 Tks a lot for the update.
